"""Original A1 starter vocabulary written specifically for French learners."""
from __future__ import annotations


def _noun(fr, tr, en, article, gender, plural, rank, deck):
    phrase = f"{article}{fr}" if article.endswith("'") else f"{article} {fr}"
    return {"fr": fr, "tr": tr, "en": en, "article": article, "gender": gender, "plural": plural,
            "part_of_speech": "noun", "example_fr": f"C'est {phrase}.", "example_tr": f"Bu, {tr}.",
            "example_en": f"This is the {en}.", "frequency_rank": rank, "deck": deck, "audio": ""}


def _word(fr, tr, en, pos, ex_fr, ex_tr, ex_en, rank, deck):
    return {"fr": fr, "tr": tr, "en": en, "article": "", "gender": "", "plural": "",
            "part_of_speech": pos, "example_fr": ex_fr, "example_tr": ex_tr, "example_en": ex_en,
            "frequency_rank": rank, "deck": deck, "audio": ""}


_NOUN_DATA = [
    ("homme", "adam", "man", "l'", "masculine", "hommes", "İnsanlar"),
    ("femme", "kadın", "woman", "la", "feminine", "femmes", "İnsanlar"),
    ("enfant", "çocuk", "child", "l'", "masculine/feminine", "enfants", "İnsanlar"),
    ("garçon", "erkek çocuk", "boy", "le", "masculine", "garçons", "İnsanlar"),
    ("fille", "kız çocuk", "girl", "la", "feminine", "filles", "İnsanlar"),
    ("ami", "erkek arkadaş", "friend", "l'", "masculine", "amis", "İnsanlar"),
    ("amie", "kadın arkadaş", "friend", "l'", "feminine", "amies", "İnsanlar"),
    ("mère", "anne", "mother", "la", "feminine", "mères", "Aile"),
    ("père", "baba", "father", "le", "masculine", "pères", "Aile"),
    ("frère", "erkek kardeş", "brother", "le", "masculine", "frères", "Aile"),
    ("sœur", "kız kardeş", "sister", "la", "feminine", "sœurs", "Aile"),
    ("famille", "aile", "family", "la", "feminine", "familles", "Aile"),
    ("nom", "isim", "name", "le", "masculine", "noms", "Temel"),
    ("professeur", "öğretmen", "teacher", "le", "masculine/feminine", "professeurs", "Okul"),
    ("élève", "öğrenci", "pupil", "l'", "masculine/feminine", "élèves", "Okul"),
    ("médecin", "doktor", "doctor", "le", "masculine/feminine", "médecins", "Meslekler"),
    ("maison", "ev", "house", "la", "feminine", "maisons", "Ev"),
    ("appartement", "daire", "apartment", "l'", "masculine", "appartements", "Ev"),
    ("chambre", "oda", "room", "la", "feminine", "chambres", "Ev"),
    ("cuisine", "mutfak", "kitchen", "la", "feminine", "cuisines", "Ev"),
    ("salle de bains", "banyo", "bathroom", "la", "feminine", "salles de bains", "Ev"),
    ("porte", "kapı", "door", "la", "feminine", "portes", "Ev"),
    ("fenêtre", "pencere", "window", "la", "feminine", "fenêtres", "Ev"),
    ("table", "masa", "table", "la", "feminine", "tables", "Ev"),
    ("chaise", "sandalye", "chair", "la", "feminine", "chaises", "Ev"),
    ("lit", "yatak", "bed", "le", "masculine", "lits", "Ev"),
    ("lampe", "lamba", "lamp", "la", "feminine", "lampes", "Ev"),
    ("clé", "anahtar", "key", "la", "feminine", "clés", "Ev"),
    ("livre", "kitap", "book", "le", "masculine", "livres", "Okul"),
    ("cahier", "defter", "notebook", "le", "masculine", "cahiers", "Okul"),
    ("stylo", "kalem", "pen", "le", "masculine", "stylos", "Okul"),
    ("école", "okul", "school", "l'", "feminine", "écoles", "Okul"),
    ("langue", "dil", "language", "la", "feminine", "langues", "Okul"),
    ("mot", "kelime", "word", "le", "masculine", "mots", "Okul"),
    ("question", "soru", "question", "la", "feminine", "questions", "Okul"),
    ("réponse", "cevap", "answer", "la", "feminine", "réponses", "Okul"),
    ("ville", "şehir", "city", "la", "feminine", "villes", "Yerler"),
    ("pays", "ülke", "country", "le", "masculine", "pays", "Yerler"),
    ("rue", "sokak", "street", "la", "feminine", "rues", "Yerler"),
    ("place", "meydan", "square", "la", "feminine", "places", "Yerler"),
    ("gare", "tren istasyonu", "station", "la", "feminine", "gares", "Ulaşım"),
    ("aéroport", "havaalanı", "airport", "l'", "masculine", "aéroports", "Ulaşım"),
    ("hôtel", "otel", "hotel", "l'", "masculine", "hôtels", "Seyahat"),
    ("restaurant", "restoran", "restaurant", "le", "masculine", "restaurants", "Seyahat"),
    ("magasin", "mağaza", "shop", "le", "masculine", "magasins", "Alışveriş"),
    ("marché", "pazar", "market", "le", "masculine", "marchés", "Alışveriş"),
    ("voiture", "araba", "car", "la", "feminine", "voitures", "Ulaşım"),
    ("bus", "otobüs", "bus", "le", "masculine", "bus", "Ulaşım"),
    ("train", "tren", "train", "le", "masculine", "trains", "Ulaşım"),
    ("vélo", "bisiklet", "bicycle", "le", "masculine", "vélos", "Ulaşım"),
    ("billet", "bilet", "ticket", "le", "masculine", "billets", "Ulaşım"),
    ("eau", "su", "water", "l'", "feminine", "eaux", "Yiyecek"),
    ("pain", "ekmek", "bread", "le", "masculine", "pains", "Yiyecek"),
    ("lait", "süt", "milk", "le", "masculine", "laits", "Yiyecek"),
    ("café", "kahve", "coffee", "le", "masculine", "cafés", "Yiyecek"),
    ("thé", "çay", "tea", "le", "masculine", "thés", "Yiyecek"),
    ("pomme", "elma", "apple", "la", "feminine", "pommes", "Yiyecek"),
    ("banane", "muz", "banana", "la", "feminine", "bananes", "Yiyecek"),
    ("pomme de terre", "patates", "potato", "la", "feminine", "pommes de terre", "Yiyecek"),
    ("tomate", "domates", "tomato", "la", "feminine", "tomates", "Yiyecek"),
    ("fromage", "peynir", "cheese", "le", "masculine", "fromages", "Yiyecek"),
    ("œuf", "yumurta", "egg", "l'", "masculine", "œufs", "Yiyecek"),
    ("viande", "et", "meat", "la", "feminine", "viandes", "Yiyecek"),
    ("poisson", "balık", "fish", "le", "masculine", "poissons", "Yiyecek"),
    ("soupe", "çorba", "soup", "la", "feminine", "soupes", "Yiyecek"),
    ("petit déjeuner", "kahvaltı", "breakfast", "le", "masculine", "petits déjeuners", "Yiyecek"),
    ("tête", "baş", "head", "la", "feminine", "têtes", "Vücut"),
    ("main", "el", "hand", "la", "feminine", "mains", "Vücut"),
    ("œil", "göz", "eye", "l'", "masculine", "yeux", "Vücut"),
    ("oreille", "kulak", "ear", "l'", "feminine", "oreilles", "Vücut"),
    ("bouche", "ağız", "mouth", "la", "feminine", "bouches", "Vücut"),
    ("pied", "ayak", "foot", "le", "masculine", "pieds", "Vücut"),
    ("jour", "gün", "day", "le", "masculine", "jours", "Zaman"),
    ("semaine", "hafta", "week", "la", "feminine", "semaines", "Zaman"),
    ("mois", "ay", "month", "le", "masculine", "mois", "Zaman"),
    ("année", "yıl", "year", "l'", "feminine", "années", "Zaman"),
    ("matin", "sabah", "morning", "le", "masculine", "matins", "Zaman"),
    ("soir", "akşam", "evening", "le", "masculine", "soirs", "Zaman"),
    ("heure", "saat", "hour", "l'", "feminine", "heures", "Zaman"),
    ("temps", "hava; zaman", "weather; time", "le", "masculine", "temps", "Doğa"),
    ("soleil", "güneş", "sun", "le", "masculine", "soleils", "Doğa"),
    ("pluie", "yağmur", "rain", "la", "feminine", "pluies", "Doğa"),
    ("neige", "kar", "snow", "la", "feminine", "neiges", "Doğa"),
    ("arbre", "ağaç", "tree", "l'", "masculine", "arbres", "Doğa"),
    ("fleur", "çiçek", "flower", "la", "feminine", "fleurs", "Doğa"),
    ("chien", "köpek", "dog", "le", "masculine", "chiens", "Hayvanlar"),
    ("chat", "kedi", "cat", "le", "masculine", "chats", "Hayvanlar"),
    ("travail", "iş", "work", "le", "masculine", "travaux", "Günlük"),
    ("bureau", "ofis", "office", "le", "masculine", "bureaux", "Günlük"),
    ("argent", "para", "money", "l'", "masculine", "-", "Alışveriş"),
    ("prix", "fiyat", "price", "le", "masculine", "prix", "Alışveriş"),
    ("téléphone", "telefon", "telephone", "le", "masculine", "téléphones", "Günlük"),
    ("ordinateur", "bilgisayar", "computer", "l'", "masculine", "ordinateurs", "Günlük"),
    ("musique", "müzik", "music", "la", "feminine", "musiques", "Boş Zaman"),
    ("film", "film", "film", "le", "masculine", "films", "Boş Zaman"),
    ("jeu", "oyun", "game", "le", "masculine", "jeux", "Boş Zaman"),
    ("anniversaire", "doğum günü", "birthday", "l'", "masculine", "anniversaires", "Günlük"),
    ("aide", "yardım", "help", "l'", "feminine", "aides", "Temel"),
    ("chemise", "gömlek", "shirt", "la", "feminine", "chemises", "Giyim"),
    ("robe", "elbise", "dress", "la", "feminine", "robes", "Giyim"),
    ("chaussure", "ayakkabı", "shoe", "la", "feminine", "chaussures", "Giyim"),
]

WORDS = [_noun(fr, tr, en, article, gender, plural, i + 1, deck)
         for i, (fr, tr, en, article, gender, plural, deck) in enumerate(_NOUN_DATA)]

_OTHER_DATA = [
    ("être", "olmak", "to be", "verb", "Je suis à la maison.", "Evdeyim.", "I am at home.", "Fiiller"),
    ("avoir", "sahip olmak", "to have", "verb", "Nous avons deux enfants.", "İki çocuğumuz var.", "We have two children.", "Fiiller"),
    ("s'appeler", "adı olmak", "to be called", "verb", "Je m'appelle Léa.", "Benim adım Léa.", "My name is Léa.", "Fiiller"),
    ("habiter", "oturmak", "to live", "verb", "J'habite à Paris.", "Paris'te oturuyorum.", "I live in Paris.", "Fiiller"),
    ("venir", "gelmek", "to come", "verb", "Elle vient de Lyon.", "O, Lyon'dan geliyor.", "She comes from Lyon.", "Fiiller"),
    ("aller", "gitmek", "to go", "verb", "Nous allons à l'école.", "Okula gidiyoruz.", "We go to school.", "Fiiller"),
    ("faire", "yapmak", "to do", "verb", "Que fais-tu aujourd'hui ?", "Bugün ne yapıyorsun?", "What are you doing today?", "Fiiller"),
    ("apprendre", "öğrenmek", "to learn", "verb", "J'apprends le français.", "Fransızca öğreniyorum.", "I am learning French.", "Fiiller"),
    ("travailler", "çalışmak", "to work", "verb", "Mon père travaille ici.", "Babam burada çalışıyor.", "My father works here.", "Fiiller"),
    ("parler", "konuşmak", "to speak", "verb", "Vous parlez anglais ?", "İngilizce konuşuyor musunuz?", "Do you speak English?", "Fiiller"),
    ("dire", "söylemek", "to say", "verb", "Dis-moi ton nom.", "Bana adını söyle.", "Tell me your name.", "Fiiller"),
    ("demander", "sormak", "to ask", "verb", "Je demande au professeur.", "Öğretmene soruyorum.", "I ask the teacher.", "Fiiller"),
    ("répondre", "cevap vermek", "to answer", "verb", "Elle répond en français.", "Fransızca cevap veriyor.", "She answers in French.", "Fiiller"),
    ("lire", "okumak", "to read", "verb", "Il lit un livre.", "Bir kitap okuyor.", "He is reading a book.", "Fiiller"),
    ("écrire", "yazmak", "to write", "verb", "J'écris un message.", "Bir mesaj yazıyorum.", "I am writing a message.", "Fiiller"),
    ("écouter", "dinlemek", "to listen", "verb", "Nous écoutons de la musique.", "Müzik dinliyoruz.", "We listen to music.", "Fiiller"),
    ("voir", "görmek", "to see", "verb", "Je vois le train.", "Treni görüyorum.", "I see the train.", "Fiiller"),
    ("manger", "yemek", "to eat", "verb", "L'enfant mange une pomme.", "Çocuk bir elma yiyor.", "The child is eating an apple.", "Fiiller"),
    ("boire", "içmek", "to drink", "verb", "Tu veux boire du thé ?", "Çay içmek ister misin?", "Do you want to drink tea?", "Fiiller"),
    ("acheter", "satın almak", "to buy", "verb", "Nous achetons du pain frais.", "Taze ekmek alıyoruz.", "We buy fresh bread.", "Fiiller"),
    ("payer", "ödemek", "to pay", "verb", "Je paie par carte.", "Kartla ödüyorum.", "I pay by card.", "Fiiller"),
    ("avoir besoin", "ihtiyacı olmak", "to need", "verb", "J'ai besoin d'aide.", "Yardıma ihtiyacım var.", "I need help.", "Fiiller"),
    ("aimer", "sevmek", "to like", "verb", "Nous aimons ce film.", "Bu filmi seviyoruz.", "We like this film.", "Fiiller"),
    ("vouloir", "istemek", "to want", "verb", "Je voudrais un café.", "Bir kahve istiyorum.", "I would like a coffee.", "Fiiller"),
    ("pouvoir", "-ebilmek", "can", "verb", "Pouvez-vous m'aider ?", "Bana yardım edebilir misiniz?", "Can you help me?", "Fiiller"),
    ("devoir", "zorunda olmak", "must", "verb", "Je dois partir maintenant.", "Şimdi gitmek zorundayım.", "I must leave now.", "Fiiller"),
    ("donner", "vermek", "to give", "verb", "Donne-moi le livre, s'il te plaît.", "Lütfen kitabı bana ver.", "Please give me the book.", "Fiiller"),
    ("prendre", "almak", "to take", "verb", "Je prends le train.", "Trene biniyorum.", "I take the train.", "Fiiller"),
    ("trouver", "bulmak", "to find", "verb", "Elle trouve la clé.", "Anahtarı buluyor.", "She finds the key.", "Fiiller"),
    ("chercher", "aramak", "to look for", "verb", "Je cherche un hôtel.", "Bir otel arıyorum.", "I am looking for a hotel.", "Fiiller"),
    ("ouvrir", "açmak", "to open", "verb", "Ouvrez la fenêtre, s'il vous plaît.", "Lütfen pencereyi açın.", "Please open the window.", "Fiiller"),
    ("fermer", "kapatmak", "to close", "verb", "Il ferme la porte.", "Kapıyı kapatıyor.", "He closes the door.", "Fiiller"),
    ("dormir", "uyumak", "to sleep", "verb", "Le bébé dort.", "Bebek uyuyor.", "The baby is sleeping.", "Fiiller"),
    ("se lever", "kalkmak", "to get up", "verb", "Je me lève à sept heures.", "Saat yedide kalkıyorum.", "I get up at seven.", "Fiiller"),
    ("partir", "ayrılmak", "to leave", "verb", "Le train part à neuf heures.", "Tren saat dokuzda kalkıyor.", "The train leaves at nine.", "Fiiller"),
    ("bon", "iyi", "good", "adjective", "Le café est bon.", "Kahve iyi.", "The coffee is good.", "Sıfatlar"),
    ("mauvais", "kötü", "bad", "adjective", "Il fait mauvais aujourd'hui.", "Bugün hava kötü.", "The weather is bad today.", "Sıfatlar"),
    ("grand", "büyük", "big", "adjective", "Paris est une grande ville.", "Paris büyük bir şehirdir.", "Paris is a big city.", "Sıfatlar"),
    ("petit", "küçük", "small", "adjective", "La chambre est petite.", "Oda küçük.", "The room is small.", "Sıfatlar"),
    ("nouveau", "yeni", "new", "adjective", "Mon vélo est nouveau.", "Bisikletim yeni.", "My bicycle is new.", "Sıfatlar"),
    ("vieux", "eski; yaşlı", "old", "adjective", "C'est une vieille maison.", "Bu eski bir ev.", "It is an old house.", "Sıfatlar"),
    ("jeune", "genç", "young", "adjective", "La professeure est jeune.", "Öğretmen genç.", "The teacher is young.", "Sıfatlar"),
    ("beau", "güzel", "beautiful", "adjective", "Le jardin est beau.", "Bahçe güzel.", "The garden is beautiful.", "Sıfatlar"),
    ("rapide", "hızlı", "fast", "adjective", "Le train est rapide.", "Tren hızlı.", "The train is fast.", "Sıfatlar"),
    ("lent", "yavaş", "slow", "adjective", "Parlez lentement, s'il vous plaît.", "Lütfen yavaş konuşun.", "Please speak slowly.", "Sıfatlar"),
    ("chaud", "sıcak", "hot", "adjective", "La soupe est chaude.", "Çorba sıcak.", "The soup is hot.", "Sıfatlar"),
    ("froid", "soğuk", "cold", "adjective", "L'eau est froide.", "Su soğuk.", "The water is cold.", "Sıfatlar"),
    ("cher", "pahalı", "expensive", "adjective", "L'hôtel est cher.", "Otel pahalı.", "The hotel is expensive.", "Sıfatlar"),
    ("facile", "kolay", "easy", "adjective", "Cet exercice est facile.", "Bu alıştırma kolay.", "This exercise is easy.", "Sıfatlar"),
    ("difficile", "zor", "difficult", "adjective", "La question est difficile.", "Soru zor.", "The question is difficult.", "Sıfatlar"),
    ("aujourd'hui", "bugün", "today", "adverb", "Aujourd'hui, j'ai le temps.", "Bugün zamanım var.", "I have time today.", "Zaman"),
    ("demain", "yarın", "tomorrow", "adverb", "Demain, nous ne travaillons pas.", "Yarın çalışmıyoruz.", "We do not work tomorrow.", "Zaman"),
    ("maintenant", "şimdi", "now", "adverb", "Je viens maintenant.", "Şimdi geliyorum.", "I am coming now.", "Zaman"),
    ("ici", "burada", "here", "adverb", "Nous habitons ici.", "Burada oturuyoruz.", "We live here.", "Temel"),
    ("là", "orada", "there", "adverb", "La gare est là.", "İstasyon orada.", "The station is there.", "Temel"),
    ("s'il vous plaît", "lütfen", "please", "expression", "Un café, s'il vous plaît.", "Bir kahve, lütfen.", "A coffee, please.", "Temel"),
    ("merci", "teşekkürler", "thank you", "expression", "Merci pour votre aide.", "Yardımınız için teşekkürler.", "Thank you for your help.", "Temel"),
    ("oui", "evet", "yes", "particle", "Oui, c'est vrai.", "Evet, doğru.", "Yes, that is true.", "Temel"),
    ("non", "hayır", "no", "particle", "Non, pas aujourd'hui.", "Hayır, bugün değil.", "No, not today.", "Temel"),
    ("et", "ve", "and", "conjunction", "Léa et Marc apprennent le français.", "Léa ve Marc Fransızca öğreniyor.", "Léa and Marc learn French.", "Temel"),
    ("mais", "ama", "but", "conjunction", "Petit mais confortable.", "Küçük ama rahat.", "Small but comfortable.", "Temel"),
]

_start = len(WORDS) + 1
WORDS.extend(_word(fr, tr, en, pos, ex_fr, ex_tr, ex_en, _start + i, deck)
             for i, (fr, tr, en, pos, ex_fr, ex_tr, ex_en, deck) in enumerate(_OTHER_DATA))
A1_WORDS = WORDS


def count(): return len(WORDS)
def decks(): return sorted({w["deck"] for w in WORDS})
